# Generated by Django 4.2.4 on 2023-08-15 19:14

import FruitipediaApp.account.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccountModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=25, validators=[django.core.validators.MinLengthValidator(2), FruitipediaApp.account.validators.validate_name])),
                ('last_name', models.CharField(max_length=35, validators=[django.core.validators.MinLengthValidator(1), FruitipediaApp.account.validators.validate_name])),
                ('email', models.EmailField(max_length=40)),
                ('password', models.CharField(max_length=20, validators=[django.core.validators.MinLengthValidator(8)])),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('age', models.IntegerField(blank=True, default=18, null=True)),
            ],
        ),
    ]
